export const sampleProducts = [{
    "ID": 1,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 2,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 3,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 4,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 5,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 6,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 7,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 8,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 9,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
  {
    "ID": 10,
    "ClientName": "Client 1",
    "ProjectName": "Project 1",
    "TaskName": "Task 1",
    "Mon": 2,
    "Tue": 0,
    "Wed": 3,
    "Thu": 5,
    "Fri": 2,
    "Sat": 3,
    "Sun": 0,
    "Total": 12,
    "StartDate": new Date(1996, 7, 1)
  },
];